# Environment Variables
ENV_DEV_MODE = 'DYNOSCALE_DEV_MODE'
ENV_HEROKU_DYNO = 'DYNO'
ENV_DYNOSCALE_URL = 'DYNOSCALE_URL'
ENV_DYNOSCALE_DATA_DIR_NAME = "DYNOSCALE_DATA_DIR_NAME"
ENV_DYNOSCALE_DATA_FILE_NAME = "DYNOSCALE_DATA_FILE_NAME"

# Redis
ENV_REDIS_TLS_URL = 'REDIS_TLS_URL'
ENV_REDIS_URL = 'REDIS_URL'
ENV_REDISTOGO_TLS_URL = 'REDISTOGO_TLS_URL'
ENV_REDISTOGO_URL = 'REDISTOGO_URL'
ENV_OPENREDIS_TLS_URL = 'OPENREDIS_TLS_URL'
ENV_OPENREDIS_URL = 'OPENREDIS_URL'
ENV_REDISGREEN_TLS_URL = 'REDISGREEN_TLS_URL'
ENV_REDISGREEN_URL = 'REDISGREEN_URL'
ENV_REDISCLOUD_TLS_URL = 'REDISCLOUD_TLS_URL'
ENV_REDISCLOUD_URL = 'REDISCLOUD_URL'

# Header
HTTP_X_REQUEST_START = 'HTTP_X_REQUEST_START'
X_REQUEST_START = 'X-REQUEST-START'
